version: '3.7'

services:
  cashback-api-server:
    image: "node:lts-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "5000:5000"
    command: sh -c "npm install && npm run dev"
    container_name: cashback-api-server
